name: Routes Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CRUD-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Unit tests
        run: |
          npm ci
          npm run build --if-present
          npm test

  Dockerize:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jonahjkim/backend-deployment-practice:latest

  UpdateAWS:
    needs: Dockerize
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download AWS CLI
        run: |
          curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh
          chmod +x install-aws.sh
          ./install-aws.sh "v2" "amd64"
          rm install-aws.sh 

      - name: Configure credentials
        run: |
          echo -e "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          aws ecs update-service --cluster "backend-deployment-practice" --service "backend-deployment-serviceeee" --force-new-deployment --region "us-west-2"