name: Routes Test
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  CRUD-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}


      - name: Default '/' route test
        run: |
          npm ci
          node index.js &
          sleep 5
          node index.js
      - run: curl http://localhost:3000