name: Routes Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CRUD-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Unit tests
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Dockerize and test dockerized
        run: |
          docker login 
          jonahjkim
          08!$JxtmCPro12
          docker build . -t backend-deployment-practice
