name: Routes Test
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  CRUD-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit tests
        run: |
          ifconfig
          npm ci
          npm run build --if-present
          npm test