name: Routes Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CRUD-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Default '/' route test
        run: |
          npm ci
          node index.js &
          sleep 5
          curl http://localhost:3000